spring.application.name=Docdrift

# Server Config
server.port=8080

# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/docdrift
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# GitHub API Settings
github.api.url=https://api.github.com
github.api.token=${GITHUB_PAT:}

# Gemini API Settings
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.key=${GEMINI_API_KEY:}

